#version 460

layout (local_size_x = 16, local_size_y = 16) in;

// Common descriptor set
layout(set = 0, binding = 0) uniform UniformBuffer
{
    vec2 windowSize;
    vec2 inputTexSize;
} UB;

// private descriptor set
layout(rgba16f,set = 1, binding = 0) uniform image2D image;
layout(set = 1, binding = 1) uniform sampler2D inputTex;

void main()
{
    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);

    if(pixelCoord.x < UB.windowSize.x && pixelCoord.y < UB.windowSize.y)
    {
        vec2 UV = vec2(pixelCoord) / UB.windowSize;

        vec3 color = texture(inputTex, UV).xyz;
        imageStore(image, pixelCoord, vec4(color, 1.0));
    }
}