#version 460

layout (local_size_x = 16, local_size_y = 16) in;

layout(rgba16f,set = 0, binding = 0) uniform image2D image;

layout(set = 0, binding = 1) uniform sampler2D inputTex;

void main()
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(image);

    if(texelCoord.x < size.x && texelCoord.y < size.y)
    {
        vec2 drawSize = vec2(size.xy);
        vec2 UV = vec2(texelCoord.xy) / drawSize.xy;

        vec3 color = texture(inputTex, UV).xyz;
        imageStore(image, texelCoord, vec4(color, 1.0));
    }
}